# -*- coding: utf-8 -*-
"""FIAP_TechChallenge-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YSRfjkWlU5cYxl87lvvOBYKeUcsspSS

# 📚 Predictive Analysis of Cancer
---
This project explores the Breast Cancer Wisconsin Dataset with the goal of classifying tumors as benign or malignant. Exploratory analyses and tests were performed using four machine learning models — Logistic Regression, Random Forest, Gradient Boosting, and KNN — to identify the best predictive approach.


https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data/data

## 1. 🟦 Load Data


---

### 1.1. 📗 Library Imports
"""

!pip install pyreaddbc --upgrade -q
!pip install dbfread -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# Exploratory Analysis
from scipy.stats import ttest_ind
from sklearn.ensemble import RandomForestClassifier
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Modeling setup
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, f1_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier

import shap

"""### 1.2. 📗 Read File

"""

df = pd.read_csv('https://raw.githubusercontent.com/bschoola/FIAP-Pos-AI/refs/heads/main/Data/data.csv', encoding="utf-8-sig")

"""### 1.4. 📗 Translate columns to Portuguese and drop unusable columns



"""

# rename fields
renomear = {
    "diagnosis": "diagnostico",
    "radius_mean": "raio_medio",
    "texture_mean": "textura_media",
    "perimeter_mean": "perimetro_medio",
    "area_mean": "area_media",
    "smoothness_mean": "suavidade_media",
    "compactness_mean": "compacidade_media",
    "concavity_mean": "concavidade_media",
    "concave points_mean": "pontos_concavos_media",
    "symmetry_mean": "simetria_media",
    "fractal_dimension_mean": "dimensao_fractal_media",
    "radius_se": "raio_erro_padrao",
    "texture_se": "textura_erro_padrao",
    "perimeter_se": "perimetro_erro_padrao",
    "area_se": "area_erro_padrao",
    "smoothness_se": "suavidade_erro_padrao",
    "compactness_se": "compacidade_erro_padrao",
    "concavity_se": "concavidade_erro_padrao",
    "concave points_se": "pontos_concavos_erro_padrao",
    "symmetry_se": "simetria_erro_padrao",
    "fractal_dimension_se": "dimensao_fractal_erro_padrao",
    "radius_worst": "raio_pior",
    "texture_worst": "textura_pior",
    "perimeter_worst": "perimetro_pior",
    "area_worst": "area_pior",
    "smoothness_worst": "suavidade_pior",
    "compactness_worst": "compacidade_pior",
    "concavity_worst": "concavidade_pior",
    "concave points_worst": "pontos_concavos_pior",
    "symmetry_worst": "simetria_pior",
    "fractal_dimension_worst": "dimensao_fractal_pior"
}

df = df.rename(columns=renomear)

# The Unnamed feature is completely empty, so we will remove it.

df = df.drop(columns=["Unnamed: 32"], errors='ignore')

"""## 2. 🟦 Modeling
---

### 2.1. 💻 Modeling Setup

#### 2.1.1. 🧠 Train and Test Split
"""

# copy
df_bi = df.copy()

# binary target
df_bi['diagnostico_binario'] = df_bi['diagnostico'].map({'M': 1, 'B': 0})

selected_features = [ 'area_pior', 'textura_pior', 'pontos_concavos_pior', 'concavidade_pior' ]

# 🔥 keep only the necessary columns
df_modelo = df_bi[selected_features + ['diagnostico_binario']].copy()

# separate X and y
X = df_modelo[selected_features]
y = df_modelo['diagnostico_binario']

# train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""### 2.2. 🚀 Modeling

#### 2.2.2. 🧠 Model - Logistic Regression
"""

# pipeline with normalization
pipe_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=1000))
])

# training
pipe_lr.fit(X_train, y_train)

# prediction
y_pred = pipe_lr.predict(X_test)
y_prob = pipe_lr.predict_proba(X_test)[:,1]

# metrics
print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("F1-score:", f1_score(y_test, y_pred))

"""#### 2.2.3. 🧠 Model - Random Forest

"""

model_rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

model_rf.fit(X_train, y_train)

y_pred = model_rf.predict(X_test)
y_prob = model_rf.predict_proba(X_test)[:,1]

print("Random Forest")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("F1-score:", f1_score(y_test, y_pred))

"""#### 2.2.4. 🧠 Model - Gradient Boosting (XGBoost or similar)

"""

model_gb = GradientBoostingClassifier(random_state=42)

model_gb.fit(X_train, y_train)

y_pred = model_gb.predict(X_test)
y_prob = model_gb.predict_proba(X_test)[:,1]

print("Gradient Boosting")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("F1-score:", f1_score(y_test, y_pred))

"""#### 2.2.5. 🧠 Model - KNN (K Neighbors Classifier)

"""

# pipeline (ESSENTIAL to normalize for KNN)
pipe_knn = Pipeline([
    ('scaler', StandardScaler()),
    ('model', KNeighborsClassifier(n_neighbors=5))
])

# training
pipe_knn.fit(X_train, y_train)

# prediction
y_pred = pipe_knn.predict(X_test)
y_prob = pipe_knn.predict_proba(X_test)[:,1]

# metrics
print("KNN")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("F1-score:", f1_score(y_test, y_pred))

"""✅ Analysis: KNN does not use feature importance; instead, it determines classification based on the proximity to neighboring data points.

#### 2.2.6. 🧠 Cross-validation: Which model is most consistent and reliable?
"""

models = {
    "Logistic Regression": pipe_lr,
    "Random Forest": model_rf,
    "Gradient Boosting": model_gb,
    "KNN": pipe_knn
}

scoring = {
    "recall": "recall",
    "f1": "f1"
}

for name, model in models.items():
    scores = cross_validate(model, X, y, cv=10, scoring=scoring)

    recall_mean = scores["test_recall"].mean()
    f1_mean = scores["test_f1"].mean()

    print(f"{name}")
    print(f"  Mean Recall: {recall_mean:.4f}")
    print(f"  Mean F1-score: {f1_mean:.4f}")
    print("-" * 30)

"""##### ✅ Analysis:

In our evaluation, a `False Negative` is a much more dangerous outcome for the patient, as it would prevent them from starting treatment as soon as possible. In this case, `Recall` would be the most appropriate metric.

However, in a hospital prediction system evaluated later by a doctor, the `F1-Score` could be more appropriate since it penalizes both precision and recall.

In both cases, `Logistic Regression` performed best in our analysis.

Legend:

*   Accuracy: How many predictions are correct overall.
*   Precision: Among those the model classified as malignant, how many were correct.
*   Recall: Among the actual malignant cases in the test set, how many were correctly identified.
*   F1-Score: The model is balanced between precision and recall.
*   ROC_AUC: How well our model separated malignant from benign.

##### 3.2.6.1. ❓ SHAP
"""

scaler = pipe_lr.named_steps['scaler']
model = pipe_lr.named_steps['model']

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

explainer = shap.LinearExplainer(model, X_train_scaled)
shap_values = explainer.shap_values(X_test_scaled)

shap.summary_plot(shap_values, X_test_scaled, feature_names=X.columns)

# transform data with scaler
X_train_scaled = pipe_lr.named_steps['scaler'].transform(X_train)

# get internal model
model_lr = pipe_lr.named_steps['model']

# linear explainer
explainer_lr = shap.LinearExplainer(model_lr, X_train_scaled)

shap_values_lr = explainer_lr.shap_values(X_train_scaled)

# 🔥 VERY IMPORTANT: use X_train in the plot
shap.summary_plot(shap_values_lr, X_train)

"""✅ Analysis: The feature `area_pior` has the greatest impact on the model output.

###### 📖 SHAP -> Benign Case
"""

shap.initjs()

shap.force_plot(
    explainer.expected_value,
    shap_values[0],
    X_test_scaled[0],
    feature_names=X.columns
)

"""###### 📖 SHAP -> Malignant Case

"""

shap.initjs()

shap.force_plot(
    explainer.expected_value,
    shap_values[1],
    X_test_scaled[1],
    feature_names=X.columns
)

"""##### 3.2.6.2. ❓ Feature Importance: Which variables does the model use most to make decisions?

"""

# get coefficients
coef = pipe_lr.named_steps['model'].coef_[0]

# associate with features
coef_df = pd.DataFrame({
    'variable': X.columns,
    'coefficient': coef
}).sort_values(by='coefficient', ascending=False)

coef_df